### ISSUE TITLE
The possible intersection between train and test split for ImageNet experiment

### ISSUE THREAD

**Issue by sunyiyou** [snap-stanford/orca#1]
Hi. 

I noticed in

https://github.com/snap-stanford/orca/blob/main/orca_imagenet.py#L171
`train_unlabel_set = datasets.ImageNetDataset(root=args.dataset_root, anno_file='./data/ImageNet100_unlabel_{}_{:.1f}.txt'.format(args.labeled_num, args.labeled_ratio), transform=TransformTwice(transform_train))`

and 

https://github.com/snap-stanford/orca/blob/main/orca_imagenet.py#L177
`test_unlabel_set = datasets.ImageNetDataset(root=args.dataset_root, anno_file='./data/ImageNet100_unlabel_50_0.5.txt', transform=transform_test)`

are possibly using the same file according to the instruction. 

Just want to double check that the files should be differently generated from the ImageNet val and train folder separately. 

If that is the case, would you mind sharing your index file since it is randomly generated? That would make it fair for the comparison between different methods. 

Thanks!

**Comment by kaidic** [comment]
Hi,

Thanks for your question. In the paper, we directly test on the unlabeled data in the training set, and it corresponds to the code above. I personally feel either testing on unlabeled training data or unlabeled test data makes sense. So I guess you could always use the validation split to do your own evaluation.

I shared one of the lists we used here:
https://drive.google.com/drive/folders/1Hy3h63Kd-hZS-yvH__SpwSQUCEmn7d-7?usp=sharing

**Comment by jingzhengli** [comment]
> Hi.
> 
> I noticed in
> 
> https://github.com/snap-stanford/orca/blob/main/orca_imagenet.py#L171 `train_unlabel_set = datasets.ImageNetDataset(root=args.dataset_root, anno_file='./data/ImageNet100_unlabel_{}_{:.1f}.txt'.format(args.labeled_num, args.labeled_ratio), transform=TransformTwice(transform_train))`
> 
> and
> 
> https://github.com/snap-stanford/orca/blob/main/orca_imagenet.py#L177 `test_unlabel_set = datasets.ImageNetDataset(root=args.dataset_root, anno_file='./data/ImageNet100_unlabel_50_0.5.txt', transform=transform_test)`
> 
> are possibly using the same file according to the instruction.
> 
> Just want to double check that the files should be differently generated from the ImageNet val and train folder separately.
> 
> If that is the case, would you mind sharing your index file since it is randomly generated? That would make it fair for the comparison between different methods.
> 
> Thanks!

Hi, could you provide the download link of imagenet? Thanks
