### ISSUE TITLE
The dataset of CIFAR100

### ISSUE THREAD

**Issue by RikkiXu** [snap-stanford/orca#2]
Hi, 
Thanks for releasing this code!
I notice that the  train_unlabel_set and the test_set of CIFAR100 are from the same file: ‘./datasets/cifar-100-python/train’. This confuses me, and I think the test_set should come from  ‘./datasets/cifar-100-python/test’
Looking forward to your response.

**Comment by kaidic** [comment]
Hi,

Thanks for your question. In the paper, we directly test on the unlabeled data in the training set, and it corresponds to the code above. I personally feel either testing on unlabeled training data or unlabeled test data makes sense. So I guess you could always use the validation split to do your own evaluation.
