### ISSUE TITLE
unseen_acc on cifar100 dataset

### ISSUE THREAD

**Issue by RikkiXu** [snap-stanford/orca#3]
Hi, Thank you for releasing the code.
When I was running the code,  the result on the cifar100 dataset(over 200 epochs) was as follows:
orca: seen_acc: 66.02% unseen_acc: 40.30%
The unseen_acc result was 3 percentage points lower than your paper.
Do you know why? I didn't change the parameters.
Looking forward to your response.

**Comment by ShichangZh** [comment]
Hello,

Thank you for the great work and for publishing the code! I had a similar question about the unseen accuracy on the CIFAR-100 datasets.

I followed the instruction and ran the following line three times, without making any changes to the code. The maximum unseen accuracy I got was 0.4114, 0.4148, and 0.3890 for these three runs. May I ask how can I get the 43.0 reported in the paper? Any parameters I need to change?

```
python orca_cifar.py --dataset cifar100 --labeled-num 50 --labeled-ratio 0.5
```

Also, seems like there is no validation set in the script. May I ask how were the numbers in Table 2 in the paper generated? Did you take the maximum overall test accuracies?

**Comment by SakurajimaMaiii** [comment]
> 

I run this code on CIFAR-100 dataset.  The **last** epoch acc is 
_Test overall acc 0.4692, seen acc 0.6659, unseen acc 0.4144_ 
I also want to know how to get the 43.0 acc on novel class. 
Is free for author(s)  to release the stanard error across different random seeds? @kaidic

**Comment by SakurajimaMaiii** [comment]
My results over 3 random seeds:
![捕获](https://user-images.githubusercontent.com/83657651/227899903-b0e2ff8d-19dc-43de-84b9-adb2b17c0c0a.JPG)
