### ISSUE TITLE
Question about the regularization term

### ISSUE THREAD

**Issue by ShichangZh** [snap-stanford/orca#4]
Hello,

Thank you for the great work and for publishing the code! I had a question about the regularization term (Equation 6) in the paper. In the paper, this regularization term is a KL divergence, but from the following line of code, seems like it is an entropy term? May I ask why the difference? Maybe I am missing something?

https://github.com/snap-stanford/orca/blob/5f33afdeb0aa1ec51d62c9f926f265504ccf9efc/orca_cifar.py#L73

**Comment by jingzhengli** [comment]
> Hello,
> 
> Thank you for the great work and for publishing the code! I had a question about the regularization term (Equation 6) in the paper. In the paper, this regularization term is a KL divergence, but from the following line of code, seems like it is an entropy term? May I ask why the difference? Maybe I am missing something?
> 
> https://github.com/snap-stanford/orca/blob/5f33afdeb0aa1ec51d62c9f926f265504ccf9efc/orca_cifar.py#L73

Hi, actually, the code can achieve the purpose of Eq.6.
I also have some questions about "margin loss". There is no difference between the code of "margin loss" and "cross-entropy"

**Comment by jingzhengli** [comment]
> > Hello,
> > Thank you for the great work and for publishing the code! I had a question about the regularization term (Equation 6) in the paper. In the paper, this regularization term is a KL divergence, but from the following line of code, seems like it is an entropy term? May I ask why the difference? Maybe I am missing something?
> > https://github.com/snap-stanford/orca/blob/5f33afdeb0aa1ec51d62c9f926f265504ccf9efc/orca_cifar.py#L73
> 
> Hi, actually, the code can achieve the purpose of Eq.6. I also have some questions about "margin loss". There is no difference between the code of "margin loss" and "cross-entropy"

Sorry, I misunderstood the code of margin loss.

**Comment by ShichangZh** [comment]
> > Hello,
> > Thank you for the great work and for publishing the code! I had a question about the regularization term (Equation 6) in the paper. In the paper, this regularization term is a KL divergence, but from the following line of code, seems like it is an entropy term? May I ask why the difference? Maybe I am missing something?
> > https://github.com/snap-stanford/orca/blob/5f33afdeb0aa1ec51d62c9f926f265504ccf9efc/orca_cifar.py#L73
> 
> Hi, actually, the code can achieve the purpose of Eq.6. I also have some questions about "margin loss". There is no difference between the code of "margin loss" and "cross-entropy"

Well, I think there are many different objectives with subtle differences can "achieve the same purpose" intuitively. I opened the issue majorly for two reasons.
1. To make sure whether this is truly a difference between the paper and code, or this can be my misunderstanding.
2. If indeed a difference, why?

**Comment by jingzhengli** [comment]
> Hi, I think the purpose of this code is achieve the class prior probability, i.e., uniform distribution. KL divergence in the paper has the same purpose but in a better form :).

**Comment by jingzhengli** [comment]
> > > Hello,
> > > Thank you for the great work and for publishing the code! I had a question about the regularization term (Equation 6) in the paper. In the paper, this regularization term is a KL divergence, but from the following line of code, seems like it is an entropy term? May I ask why the difference? Maybe I am missing something?
> > > https://github.com/snap-stanford/orca/blob/5f33afdeb0aa1ec51d62c9f926f265504ccf9efc/orca_cifar.py#L73
> > 
> > 
> > Hi, actually, the code can achieve the purpose of Eq.6. I also have some questions about "margin loss". There is no difference between the code of "margin loss" and "cross-entropy"
> 
> Well, I think there are many different objectives with subtle differences can "achieve the same purpose" intuitively. I opened the issue majorly for two reasons.
> 
> 1. To make sure whether this is truly a difference between the paper and code, or this can be my misunderstanding.
> 2. If indeed a difference, why?

Hi, I think the purpose of this code is achieve the class prior probability, i.e., uniform distribution. KL divergence in the paper has the same purpose but in a better form :).
